name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ] # Or "master"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './timestream-renderer/package-lock.json'

      - name: Install and Build
        env:
          VITE_GIT_HASH: ${{ github.sha }}
        run: |
          cd timestream-renderer
          npm install
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './timestream-renderer/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4